### ISSUE TITLE
Retroalimentación

### ISSUE THREAD

**Issue by SoldeAbril** [raulTSantos/MTPE_TRIVIA-GAME#1]
No se detectaron errores visibles.
Solo quizá en la formulación de las preguntas y respuestas, ya que en la ultima la respuesta correcta no existía.
RPTA: A 28/07/1821
pero salia que era incorrecta:
[
![image](https://user-images.githubusercontent.com/51126328/190042427-3fca3a0f-bb9e-466d-850d-e900300d4f95.png)
](url)

**Comment by raulTSantos** [comment]
issue terminado
